version: '3.5'
services:
  test:
    build:
      context: .
      dockerfile: Dockerfile
    image: metrics-core-gen-2
    container_name: metrics-core-gen-2-test-container
#    environment:
#      # SOME_CONFIGURATION
#      - SOME_CONFIGURATION=xxx
    ports:
      - "8080:8080"
    restart: no
    volumes:
     - ${PWD}/configuration:/app/configuration
     - ${PWD}/data:/app/data
     - ${PWD}/logs:/app/logs
    healthcheck:
     test: ["CMD-SHELL", "curl -f http://localhost:8080/metrics || exit 1"]
     start_period: 30s
     interval: 30s
     timeout: 10s
     retries: 3
#     networks:
#       - askug_sidekick-backend-sandbox

