name: Build and Publish Docker Image

on:
  push:
    branches:
      - sandbox
      - develop
      - master
      - 'issue/**'
#  release:
#    types: [published]
  workflow_dispatch:

env:
  IMAGE_NAME: prototype-tessera-dfe

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Cache pip packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run tests (optional)
        run: |
          if [ -f pytest.ini ] || [ -d tests ]; then pytest; fi

  alternative-build-and-push:
    runs-on: ubuntu-latest
    container:
      image: quay.io/buildah/stable
      options: --privileged

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Get short SHA and branch name
        id: vars
        run: |
          echo "short_sha=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
          echo "branch_name=$(echo ${GITHUB_REF##*/} | tr '[:upper:]' '[:lower:]' | tr -c 'a-z0-9.-' '-')" >> $GITHUB_OUTPUT

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | buildah login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin docker.io

      - name: Build image with Buildah
        run: |
          buildah bud \
            --tag docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest \
            --tag docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:sha-${{ steps.vars.outputs.short_sha }} \
            --tag docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:branch-${{ steps.vars.outputs.branch_name }} \
            --file Dockerfile \
            .

      - name: Push image to DockerHub
        run: |
          buildah push docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
          buildah push docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:sha-${{ steps.vars.outputs.short_sha }}
          buildah push docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:branch-${{ steps.vars.outputs.branch_name }}ldah push docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:branch-${{ steps.vars.outputs.branch_name }}